CREATE DATABASE JobEngineDb
ON PRIMARY (
NAME = N'JobEngineDb',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\JobEngineDb.mdf',
SIZE = 8192 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024 KB
)
LOG ON (
NAME = N'JobEngineDb_log',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\JobEngineDb_log.ldf',
SIZE = 5120 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10 %
)
GO

ALTER DATABASE JobEngineDb
SET
ANSI_NULL_DEFAULT OFF,
ANSI_NULLS OFF,
ANSI_PADDING OFF,
ANSI_WARNINGS OFF,
ARITHABORT OFF,
AUTO_CLOSE OFF,
AUTO_CREATE_STATISTICS ON,
AUTO_SHRINK OFF,
AUTO_UPDATE_STATISTICS ON,
AUTO_UPDATE_STATISTICS_ASYNC OFF,
COMPATIBILITY_LEVEL = 150,
CONCAT_NULL_YIELDS_NULL OFF,
CURSOR_CLOSE_ON_COMMIT OFF,
CURSOR_DEFAULT GLOBAL,
DATE_CORRELATION_OPTIMIZATION OFF,
DB_CHAINING OFF,
HONOR_BROKER_PRIORITY OFF,
MULTI_USER,
NESTED_TRIGGERS = ON,
NUMERIC_ROUNDABORT OFF,
PAGE_VERIFY CHECKSUM,
PARAMETERIZATION SIMPLE,
QUOTED_IDENTIFIER OFF,
READ_COMMITTED_SNAPSHOT OFF,
RECOVERY FULL,
RECURSIVE_TRIGGERS OFF,
TRANSFORM_NOISE_WORDS = OFF,
TRUSTWORTHY OFF
WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE JobEngineDb
COLLATE SQL_Latin1_General_CP1_CI_AS
GO

ALTER DATABASE JobEngineDb
SET DISABLE_BROKER
GO

ALTER DATABASE JobEngineDb
SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE JobEngineDb
SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

ALTER DATABASE JobEngineDb
SET QUERY_STORE = OFF
GO

USE JobEngineDb
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER AUTHORIZATION ON DATABASE::JobEngineDb TO sa
GO




-- Set Table --

CREATE TABLE [dbo].[Set] (
  [Key] NVARCHAR(100) NOT NULL
 ,[Value] NVARCHAR(100) NOT NULL
 ,[Score] INT NOT NULL
 ,[ExpireAt] DATETIME NULL
 ,CONSTRAINT PK_Set__Key_Value PRIMARY KEY CLUSTERED ([Key], [Value]) WITH (IGNORE_DUP_KEY = ON)
) ON [PRIMARY]
GO

CREATE INDEX IX_Set__ExpireAt
ON [dbo].[Set] ([ExpireAt])
WHERE ([ExpireAt] IS NOT NULL)
ON [PRIMARY]
GO

CREATE INDEX IX_Set__Key_Score
ON [dbo].[Set] ([Key], [Score])
ON [PRIMARY]
GO




-- Job Table --

CREATE TABLE [dbo].[Job] (
  [Id] BIGINT IDENTITY
 ,[InvocationData] NVARCHAR(MAX) NOT NULL
 ,[Arguments] NVARCHAR(MAX) NULL
 ,[CurrentStateId] BIGINT NULL
 ,[CurrentStateName] NVARCHAR(20) NULL
 ,[CreatedAt] DATETIME NOT NULL
 ,[ExpireAt] DATETIME NULL
 ,CONSTRAINT PK_Job__Id PRIMARY KEY CLUSTERED ([Id])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX IX_Job__ExpireAt
ON [dbo].[Job] ([ExpireAt])
WHERE ([ExpireAt] IS NOT NULL)
ON [PRIMARY]
GO



-- State Table --

CREATE TABLE [dbo].[State] (
  [JobId] BIGINT NOT NULL
 ,[Id] BIGINT IDENTITY
 ,[Name] NVARCHAR(20) NULL
 ,[Reason] NVARCHAR(100) NULL
 ,[Data] NVARCHAR(MAX) NULL
 ,[CreatedAt] DATETIME NULL
 ,CONSTRAINT PK_State__JobId_Id PRIMARY KEY CLUSTERED ([JobId], [Id])
)
GO

CREATE INDEX IX_State__CreatedAt
ON [dbo].[State] ([CreatedAt])
GO

ALTER TABLE [dbo].[State]
ADD CONSTRAINT FK_State__JobId FOREIGN KEY ([JobId]) REFERENCES [dbo].[Job] ([Id]) ON DELETE CASCADE ON UPDATE CASCADE
GO